#!/bin/bash
# Warp notification utility using OSC escape sequences.
# Usage: warp-notify.sh <title> <body>
#
# For structured Warp notifications, title should be "warp://cli-agent"
# and body should be a JSON string matching the cli-agent notification schema.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/should-use-structured.sh"

# Only emit notifications when we've confirmed the Warp build can render them.
if ! should_use_structured; then
    exit 0
fi

TITLE="${1:-Notification}"
BODY="${2:-}"

# OSC 777 format: \033]777;notify;<title>;<body>\007
SEQ=$(printf '\033]777;notify;%s;%s\007' "$TITLE" "$BODY")

fail_transport() {
    # 这是稳定诊断码，不是 UI 文案；调用方可按码分类失败。
    printf '%s\n' "infinishell_codex_hook_transport_error: $1" >&2
    exit 1
}

open_terminal() {
    local candidate="$1"
    # 只接受 /dev 下的真实字符终端，拒绝普通文件、链接和控制字符。
    case "$candidate" in
        /dev/*) ;;
        *) return 1 ;;
    esac
    case "$candidate" in
        *[![:print:]]*|*' '*|*'..'*) return 1 ;;
    esac
    [ ! -L "$candidate" ] && [ -c "$candidate" ] || return 1
    exec 9>"$candidate" || return 1
    if [ ! -t 9 ]; then
        exec 9>&-
        return 1
    fi
}

open_ancestor_terminal() {
    local pid="$PPID" command_name tty_name candidate attempt
    for attempt in 1 2 3 4 5 6; do
        case "$pid" in
            ''|*[!0-9]*|0|1) return 1 ;;
        esac
        command_name=$(ps -o comm= -p "$pid" 2>/dev/null) || return 1
        command_name="${command_name##*/}"
        if [ "$command_name" = "codex" ] || [[ "$command_name" == codex-* ]]; then
            tty_name=$(ps -o tty= -p "$pid" 2>/dev/null) || return 1
            tty_name="${tty_name//[[:space:]]/}"
            case "$tty_name" in
                ''|'??'|'?') ;;
                *)
                    candidate="/dev/$tty_name"
                    open_terminal "$candidate" && return 0
                    ;;
            esac
        fi
        pid=$(ps -o ppid= -p "$pid" 2>/dev/null) || return 1
        pid="${pid//[[:space:]]/}"
    done
    return 1
}
case "$(uname -s)" in
        MINGW*|MSYS*)
            # Git Bash 无 /dev/tty 时，仍可通过已附着的 Windows 控制台输出。
            windows_root="${SYSTEMROOT:-${SystemRoot:-}}"
            windows_root="${windows_root//\\//}"
            powershell="$windows_root/System32/WindowsPowerShell/v1.0/powershell.exe"
            if [ -n "$windows_root" ] && [ -f "$powershell" ]; then
                (printf '%s' "$SEQ" | "$powershell" -NoLogo -NoProfile -NonInteractive -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKAFMAZQB0AC0AUwB0AHIAaQBjAHQATQBvAGQAZQAgAC0AVgBlAHIAcwBpAG8AbgAgADIACgAKAHQAcgB5ACAAewAKACAAIAAgACAAIwAgAOpT+4vWUyxnIWsakOV3hHbscst6oXtTkAz/DU5gUyh1n1MfdSAAaABvAG8AawAgAIR2IABKAFMATwBOACAAB2jGUZOPZVEvAJOP+lECMAoAIAAgACAAIAAkAGkAbgBwAHUAdABTAHQAcgBlAGEAbQAgAD0AIABbAEMAbwBuAHMAbwBsAGUAXQA6ADoATwBwAGUAbgBTAHQAYQBuAGQAYQByAGQASQBuAHAAdQB0ACgAKQAKACAAIAAgACAAJABiAHUAZgBmAGUAcgAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAYgB5AHQAZQBbAF0AIAA4ADEAOQAyAAoAIAAgACAAIAAkAGIAeQB0AGUAcwAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAASQBPAC4ATQBlAG0AbwByAHkAUwB0AHIAZQBhAG0ACgAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAB3AGgAaQBsAGUAIAAoACgAJABjAG8AdQBuAHQAIAA9ACAAJABpAG4AcAB1AHQAUwB0AHIAZQBhAG0ALgBSAGUAYQBkACgAJABiAHUAZgBmAGUAcgAsACAAMAAsACAAJABiAHUAZgBmAGUAcgAuAEwAZQBuAGcAdABoACkAKQAgAC0AZwB0ACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABiAHkAdABlAHMALgBMAGUAbgBnAHQAaAAgACsAIAAkAGMAbwB1AG4AdAAgAC0AZwB0ACAAMQAwADQAOAA1ADcANgApACAAewAgAHQAaAByAG8AdwAgACcATgBvAHQAaQBmAGkAYwBhAHQAaQBvAG4AIABlAHgAYwBlAGUAZABzACAAdABoAGUAIABiAHkAdABlACAAbABpAG0AaQB0ACcAIAB9AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiAHkAdABlAHMALgBXAHIAaQB0AGUAKAAkAGIAdQBmAGYAZQByACwAIAAwACwAIAAkAGMAbwB1AG4AdAApAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAJAB1AHQAZgA4ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABUAGUAeAB0AC4AVQBUAEYAOABFAG4AYwBvAGQAaQBuAGcAKAAkAGYAYQBsAHMAZQAsACAAJAB0AHIAdQBlACkACgAgACAAIAAgACAAIAAgACAAJABtAGUAcwBzAGEAZwBlACAAPQAgACQAdQB0AGYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAJABiAHkAdABlAHMALgBUAG8AQQByAHIAYQB5ACgAKQApAAoAIAAgACAAIAB9ACAAZgBpAG4AYQBsAGwAeQAgAHsACgAgACAAIAAgACAAIAAgACAAJABiAHkAdABlAHMALgBEAGkAcwBwAG8AcwBlACgAKQAKACAAIAAgACAAfQAKACAAIAAgACAAaQBmACAAKAAkAG0AZQBzAHMAYQBnAGUALgBMAGUAbgBnAHQAaAAgAC0AZQBxACAAMAApACAAewAgAHQAaAByAG8AdwAgACcATgBvAHQAaQBmAGkAYwBhAHQAaQBvAG4AIABpAHMAIABlAG0AcAB0AHkAJwAgAH0ACgAgACAAIAAgACMAIACZUSAAVQBuAGkAYwBvAGQAZQAgAKdjNlLwUyAAQQBQAEkADP9/kE1RnU9WjRZiOWWoUih1N2KEdqdjNlLwU+NOAXh1mMpTIWoPXwIwCgAgACAAIAAgAEEAZABkAC0AVAB5AHAAZQAgAC0AVAB5AHAAZQBEAGUAZgBpAG4AaQB0AGkAbwBuACAAQAAnAAoAdQBzAGkAbgBnACAAUwB5AHMAdABlAG0AOwAKAHUAcwBpAG4AZwAgAFMAeQBzAHQAZQBtAC4AQwBvAG0AcABvAG4AZQBuAHQATQBvAGQAZQBsADsACgB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQAuAFIAdQBuAHQAaQBtAGUALgBJAG4AdABlAHIAbwBwAFMAZQByAHYAaQBjAGUAcwA7AAoAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGMAbABhAHMAcwAgAEkAbgBmAGkAbgBpAFMAaABlAGwAbABOAG8AdABpAGYAeQBDAG8AbgBzAG8AbABlACAAewAKACAAIAAgACAAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAIgAsACAAQwBoAGEAcgBTAGUAdAAgAD0AIABDAGgAYQByAFMAZQB0AC4AVQBuAGkAYwBvAGQAZQAsACAARQB4AGEAYwB0AFMAcABlAGwAbABpAG4AZwAgAD0AIAB0AHIAdQBlACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgAgAD0AIAB0AHIAdQBlACkAXQAKACAAIAAgACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAEkAbgB0AFAAdAByACAAQwByAGUAYQB0AGUARgBpAGwAZQBXACgAcwB0AHIAaQBuAGcAIABuAGEAbQBlACwAIAB1AGkAbgB0ACAAYQBjAGMAZQBzAHMALAAgAHUAaQBuAHQAIABzAGgAYQByAGUALAAgAEkAbgB0AFAAdAByACAAcwBlAGMAdQByAGkAdAB5ACwACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB1AGkAbgB0ACAAZABpAHMAcABvAHMAaQB0AGkAbwBuACwAIAB1AGkAbgB0ACAAZgBsAGEAZwBzACwAIABJAG4AdABQAHQAcgAgAHQAZQBtAHAAbABhAHQAZQApADsACgAgACAAIAAgAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGsAZQByAG4AZQBsADMAMgAuAGQAbABsACIALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByACAAPQAgAHQAcgB1AGUAKQBdAAoAIAAgACAAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAYgBvAG8AbAAgAEcAZQB0AEMAbwBuAHMAbwBsAGUATQBvAGQAZQAoAEkAbgB0AFAAdAByACAAaABhAG4AZABsAGUALAAgAG8AdQB0ACAAdQBpAG4AdAAgAG0AbwBkAGUAKQA7AAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACwAIABDAGgAYQByAFMAZQB0ACAAPQAgAEMAaABhAHIAUwBlAHQALgBVAG4AaQBjAG8AZABlACwAIABFAHgAYQBjAHQAUwBwAGUAbABsAGkAbgBnACAAPQAgAHQAcgB1AGUALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByACAAPQAgAHQAcgB1AGUAKQBdAAoAIAAgACAAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAYgBvAG8AbAAgAFcAcgBpAHQAZQBDAG8AbgBzAG8AbABlAFcAKABJAG4AdABQAHQAcgAgAGgAYQBuAGQAbABlACwAIABzAHQAcgBpAG4AZwAgAHQAZQB4AHQALAAgAHUAaQBuAHQAIABsAGUAbgBnAHQAaAAsACAAbwB1AHQAIAB1AGkAbgB0ACAAdwByAGkAdAB0AGUAbgAsACAASQBuAHQAUAB0AHIAIAByAGUAcwBlAHIAdgBlAGQAKQA7AAoAIAAgACAAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgAgAD0AIAB0AHIAdQBlACkAXQAKACAAIAAgACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGIAbwBvAGwAIABDAGwAbwBzAGUASABhAG4AZABsAGUAKABJAG4AdABQAHQAcgAgAGgAYQBuAGQAbABlACkAOwAKACAAIAAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAHYAbwBpAGQAIABXAHIAaQB0AGUAKABzAHQAcgBpAG4AZwAgAHQAZQB4AHQAKQAgAHsACgAgACAAIAAgACAAIAAgACAASQBuAHQAUAB0AHIAIABoAGEAbgBkAGwAZQAgAD0AIABDAHIAZQBhAHQAZQBGAGkAbABlAFcAKAAiAEMATwBOAE8AVQBUACQAIgAsACAAMAB4AEMAMAAwADAAMAAwADAAMAAsACAAMwAsACAASQBuAHQAUAB0AHIALgBaAGUAcgBvACwAIAAzACwAIAAwACwAIABJAG4AdABQAHQAcgAuAFoAZQByAG8AKQA7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAaABhAG4AZABsAGUAIAA9AD0AIABuAGUAdwAgAEkAbgB0AFAAdAByACgALQAxACkAKQAgAHQAaAByAG8AdwAgAG4AZQB3ACAAVwBpAG4AMwAyAEUAeABjAGUAcAB0AGkAbwBuACgATQBhAHIAcwBoAGEAbAAuAEcAZQB0AEwAYQBzAHQAVwBpAG4AMwAyAEUAcgByAG8AcgAoACkAKQA7AAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHUAaQBuAHQAIABtAG8AZABlADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACEARwBlAHQAQwBvAG4AcwBvAGwAZQBNAG8AZABlACgAaABhAG4AZABsAGUALAAgAG8AdQB0ACAAbQBvAGQAZQApACkAIAB0AGgAcgBvAHcAIABuAGUAdwAgAFcAaQBuADMAMgBFAHgAYwBlAHAAdABpAG8AbgAoAE0AYQByAHMAaABhAGwALgBHAGUAdABMAGEAcwB0AFcAaQBuADMAMgBFAHIAcgBvAHIAKAApACkAOwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAKABtAG8AZABlACAAJgAgADUAKQAgACEAPQAgADUAKQAgAHQAaAByAG8AdwAgAG4AZQB3ACAASQBuAHYAYQBsAGkAZABPAHAAZQByAGEAdABpAG8AbgBFAHgAYwBlAHAAdABpAG8AbgAoACIAQwBvAG4AcwBvAGwAZQAgAFYAVAAgAHAAcgBvAGMAZQBzAHMAaQBuAGcAIABpAHMAIAB1AG4AYQB2AGEAaQBsAGEAYgBsAGUAIgApADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB1AGkAbgB0ACAAdwByAGkAdAB0AGUAbgA7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAhAFcAcgBpAHQAZQBDAG8AbgBzAG8AbABlAFcAKABoAGEAbgBkAGwAZQAsACAAdABlAHgAdAAsACAAKAB1AGkAbgB0ACkAdABlAHgAdAAuAEwAZQBuAGcAdABoACwAIABvAHUAdAAgAHcAcgBpAHQAdABlAG4ALAAgAEkAbgB0AFAAdAByAC4AWgBlAHIAbwApACkACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHQAaAByAG8AdwAgAG4AZQB3ACAAVwBpAG4AMwAyAEUAeABjAGUAcAB0AGkAbwBuACgATQBhAHIAcwBoAGEAbAAuAEcAZQB0AEwAYQBzAHQAVwBpAG4AMwAyAEUAcgByAG8AcgAoACkAKQA7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAB3AHIAaQB0AHQAZQBuACAAIQA9ACAAdABlAHgAdAAuAEwAZQBuAGcAdABoACkAIAB0AGgAcgBvAHcAIABuAGUAdwAgAEkAbgB2AGEAbABpAGQATwBwAGUAcgBhAHQAaQBvAG4ARQB4AGMAZQBwAHQAaQBvAG4AKAAiAE4AbwB0AGkAZgBpAGMAYQB0AGkAbwBuACAAdwByAGkAdABlACAAdwBhAHMAIABpAG4AYwBvAG0AcABsAGUAdABlACIAKQA7AAoAIAAgACAAIAAgACAAIAAgAH0AIABmAGkAbgBhAGwAbAB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAEMAbABvAHMAZQBIAGEAbgBkAGwAZQAoAGgAYQBuAGQAbABlACkAOwAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9AAoAfQAKACcAQAAKACAAIAAgACAAWwBJAG4AZgBpAG4AaQBTAGgAZQBsAGwATgBvAHQAaQBmAHkAQwBvAG4AcwBvAGwAZQBdADoAOgBXAHIAaQB0AGUAKAAkAG0AZQBzAHMAYQBnAGUAKQAKACAAIAAgACAAZQB4AGkAdAAgADAACgB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAWwBDAG8AbgBzAG8AbABlAF0AOgA6AEUAcgByAG8AcgAuAFcAcgBpAHQAZQBMAGkAbgBlACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkACgAgACAAIAAgAGUAeABpAHQAIAAxAAoAfQAKAA==) || fail_transport "windows_console_write_failed"
            else
                fail_transport "windows_console_not_found"
            fi
            ;;
        *)
            tmux_transport=false
            if [ -n "${TMUX:-}" ]; then
                case "${TMUX_PANE:-}" in
                    %*[!0-9]*|%|'') fail_transport "invalid_tmux_pane" ;;
                    %*) ;;
                    *) fail_transport "invalid_tmux_pane" ;;
                esac
                command -v tmux >/dev/null 2>&1 || fail_transport "tmux_not_found"
                tty_target=$(tmux display-message -p -t "$TMUX_PANE" '#{pane_tty}') \
                    || fail_transport "tmux_pane_query_failed"
                open_terminal "$tty_target" || fail_transport "invalid_tmux_pane_tty"
                tmux_transport=true
            elif [ -n "${SSH_TTY:-}" ]; then
                open_terminal "$SSH_TTY" || fail_transport "invalid_ssh_tty"
            elif open_terminal /dev/tty; then
                :
            elif ! open_ancestor_terminal; then
                fail_transport "terminal_not_found"
            fi
            if [ "$tmux_transport" = true ]; then
                # tmux 需要 DCS 透传封套，内部每个 ESC 都必须双写；不修改用户透传配置。
                ESC=$'\033'
                SEQ="${SEQ//$ESC/$ESC$ESC}"
                SEQ=$(printf '\033Ptmux;%s\033\\' "$SEQ")
            fi
            printf '%s' "$SEQ" >&9 || fail_transport "terminal_write_failed"
            exec 9>&-
            ;;
    esac
